### ISSUE TITLE
自动编译

### ISSUE THREAD

**Issue by lindexi** [Firito/Dreamland.WPF.DynamicSkin#1]
```
name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: restore
      run: dotnet restore
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: msbuild
      run: msbuild
```
